import { LineMarkerMachineSpecificationsType } from "@/lib/types/product";
import { LineMarkerMachineProductKeys } from "../product-keys";

export const LineMarkerMachineSpecifications: Record<
    LineMarkerMachineProductKeys,
    LineMarkerMachineSpecificationsType
> = {
    hybrid: {
        spray_marker: `The Hybrid is a battery-powered spray line marker that applies paint via a pump through a sprayhead and nozzle.`,
        battery: `12v 14ah SLA battery allows the user to mark up to 18 soccer fields from one charge`,
        hybrid_wheel: `The unique Hybrid wheel combines the manoeuvrability of a three-wheeled marker with the efficiency of a spray marker.`,
        capacity: `Supplied with a removeable 25L tank, the Hybrid chassis is also designed to holster one of our 10L paint drums securely.`,
        line_width: `Easily adjustable line width for line widths from 50 to 120mm.`,
        usage: `Designed for use on professional natural grass surfaces like soccer fields or rugby pitches.`,
        made_in_britain: `Manufactured by hand at Pitchmark headquarters in Bristol, UK`,
        weight: `Weighs approximately 30kg when boxed.`,
        filtration_system: `High-pressure pump combined with 3-stage filtration gives consistent quality lines and fewer blockages.`,
    },
    eco_pro: {
        spray_marker: `The Eco Pro is a battery-powered spray line marker that applies paint via a pump through a sprayhead and nozzle.`,
        battery: `12v 14ah SLA battery allows the user to mark up to 18 soccer fields from one charge`,
        chassis: `Premium quality zinc coated chassic for longer life eliminating rusting.`,
        capacity: `Supplied with a 25 litre paint tank and a 6 litre water tank.`,
        line_width: `Easily adjustable line width for 50, 75, 100, 120, or 150mm wide lines.`,
        usage: `Designed for use on natural or artificial grass surfaces like soccer or rugby fields.`,
        made_in_britain: `Manufactured by hand at Pitchmark headquarters in Bristol, UK.`,
        weight: `Weghts approximately 27kg when boxed`,
        filtration_system: `High-pressure pump combined with 3-stage filtration gives consistent quality lines and fewer blockages.`,
    },
    eco_club: {
        spray_marker: `The Eco Club is a battery-powered spray line marker that applies paint via a pump through a sprayhead and nozzle.`,
        battery: `12v 14ah SLA battery allows the user to mark up to 6 soccer fields from one charge`,
        chassis: `Premium quality zinc coated chassic for longer life eliminating rusting.`,
        capacity: `The Eco Club chassic is designed to holser one of our 10L paint drums securely.`,
        line_width: `Easily adjustable line width for 50, 75, 100, 120 or 150mm wide lines.`,
        usage: `Designed for use on natural of artificial grass surfaces like soccer or rugy fields.`,
        made_in_britain: `Manufactured by hand at Pitchmark headquarters in Bristol, UK.`,
        weight: `Weighs approximately 24kg when boxed.`,
        filtration_system: `High-pressure pump combined with 3-stage filtration gives consistent quality lines and fewer blockages.`,
    },
    eco_lite: {
        spray_marker: `The Eco Lite is  battery-powered spray line marker that applies paint via a pump through a sprayhead and nozzle.`,
        battery: `12v 9ah SLA battery allows the user to mark up to 6 soccer fields from one charge.`,
        chassis: `High-density polyethyleme (HDPE) body with adjustable front end and handlebars.`,
        capacity: `The Eco Lite body holds 1 x 10L or 2 x 5L paint drums, with an optional 25L drop-in tank available.`,
        line_width: `Adjustable line width for 50 - 150mm wide lines.`,
        usage: `Designed for use on natural or artificial grass surfaces like soccer or rugby fields.`,
        made_in_britain: `Manufactured by hand at Pitchmark headquarters in Bristol, UK.`,
        weight: `Weighs approximately 23kg when boxed.`,
        filtration_system: `High-pressure pump combined with 3-stage filtration gives consistent quality lines and fewer blockages.`,
    },
    fusion: {
        spray_marker: `The Fusion is a battery-powered spray line marker that applies paint via a pump through a sprayhead and nozzle.`,
        battery: `12v 9ah SLA battery allows the user to mark up to 6 soccer fields from one charge.`,
        chassis: `High-density polyethylene (HDPE) body with adjustable front end and handlebars.`,
        capacity: `The Eco Lite body holds 1 x 10L or 2 x 5L paint drums, with an optional 25L drop-in tank available.`,
        line_width: `Adjustable line width for 50 - 150mm wide lines.`,
        usage: `Designed for use on natural or artificial grass surfaces like soccer or rugby fields.`,
        made_in_britain: `Manufactured by hand at Pitchmark headquarters in Bristol, UK.`,
        weight: `Weighs approximately 23kg when boxed.`,
        filtration_system: `High-pressue pump combined with 2-stage filtration gives consistent quality lines and fewer blockages.`,
    },
    classic: {
        chassis: `Strong poweder-coated steel frame made to a demanding specification from the best quality materials available.`,
        puncture_proof: `Solid puncture-proof wheels offer consistently smooth operation on any grass surface.`,
        transfer_wheel: `The Classic is a wheel-to-wheel marker that applies paint by transferring paint to the grass via 3 transfer wheels.`,
        capacity: `18-litre central paint resevoir capacity allowing you to mark over 2 full size soccer fields.`,
        line_width: `The Classic is available in 50, 75, 100, and 120mm line width variants.`,
        low_maintenance: `Line marking paint can remain in the bucket until the next field marking. The removeable drain plug allows you to easily empty paint for cleaning.`,
        made_in_britain: `Manufactured by hand at Pitchmark headquarters in Bristol, UK.`,
        weight: `Weighs approximately 31kg when boxed.`,
        no_rust: `Powder coated to the highest standard - no rusting!`,
    },
};
