import { ProductKey } from "./product-keys";

export const ProductFeatures: Record<ProductKey, string[]> = {
    // Machines
    javelin: [
        `Minimal Surface Disturbance Depth is infinitely variable to a maximum of 127mm (5ins).`,
        `Quick, single-lever depth setting for easy adjustment.`,
        `Cam trigger mechanism ensures that the air is always expelled at the bottom of the tine penetration, enabling treatment to be targeted precisely and consistently.`,
        `Working at 75mm (3ins) spacing, air is introduced at a rate of 88 litres (3cu.ft.) per minute.`,
        `The air injection tines are specially designed to use the maximum air available from the compressor which produces clean, fresh air at a constant rate.`,
        `Tipped tines for extra durability.`,
        `Alternative tines for other operations such as hollow coring prior to top dressing.`,
        `Wide working width.`,
        `Fast forward speed for excellent productivity.`,
        `Minimal maintenance – all bearings fully sealed and no grease nipples in the drive system.`,
        `Quiet in operation`,
    ],
    dart: [
        `Working depth of 100mm (4 ins) max.`,
        `Wide range of interchangeable tines.`,
        `Clean, vertical penetration and withdrawal without surface disturbance.`,
        `All controls, including balanced depth control, adjustable from operating position.`,
        `Easy lift” system for effortless turning and transport`,
        `Designed for ease of handling.`,
        `Minimal maintenance with sealed bearings and easily removed cover.`,
        `Effortless depth selection with clearly visible indicator.`,
        `100mm depth with minimal surface disturbance.`,
    ],
    gseries: [
        `Low ground pressure ONLY 166kg`,
        `26", 30" (760mm) or 34"(860mm) cutting width`,
        `11 quick changeover cassette options (more in development)`,
        `Trailer seat option`,
        `Strong modular construction`,
        `Lift over framework for rotproof lightweight grassbox reduces storage space and makes transport on trailers easy`,
        `Low vibration handlebars`,
        `Easy start reliable and powerful engine`,
        `Quality steel geared differential in oil bath for easy maneuverability without scuffing`,
        `Long Life drive system with quality components for reliable operation`,
        `Excellent sight lines of front roller from operators position`,
        `Cast 3 section aluminum ribbed rear roller for positive traction in all conditions`,
        `The G660/G760/G860 are easy and comfortable to operate. The handlebar console houses the controls - throttle, park brake, switches and cutter clutch. Only the forward drive handle needs to be held in by the operator. This reduces operator fatigue and with the built in electrical interlocks makes the machine ultra safe to use.`,
        `The handlebar design makes manoeuvring easy and the wide adjustment makes it comfortable for all heights.`,
        `High quality Sheffield steel cylinder and bottom blade with six blades in opposed spiral format to throw the grass evenly into the box. Adjustment of bottom blade to cylinder easy and positive with single spanner.`,
        `Large diameter front roller with adjustable scraper for precise height of cut control. Easy to adjust on both sides of machine with single spanner.`,
    ],
    es860: [
        `User Friendly easy to use keypad controls`,
        `On screen usage data`,
        `Significant reduction in HAV`,
        `No need to store petrol on site`,
        `No fumes`,
        `No risk of contaminant fluid leaks`,
        `Full battery provides 5.76kwh`,
        `3000watt (Rapid 2hr charge)`,
        `Full battery performance of > 40km / > 6hrs / approx 4 football pitches`,
        `Choice of 13 interchangeable cassettes`,
        `Easy to adjust height of cut control`,
        `Slow take up speed for smooth set off`,
        `Reverse setting`,
        `Front roller options (plain, weile & comb, brush)`,
    ],
    rotorake_600_hd: [
        `Contra rotating reels with specially designed tipped blades for a clean, consistent performance`,
        `Quick change reels for ultimate thatch control and removal all year round`,
        `User friendly operater presence contros designed for maximum operator safety`,
        `6 forward speeds for efficiency under varying conditions and depth`,
        `Reverse gear for manoeuvrability`,
        `Incorporates independent drive to the wheels and reel`,
    ],
    auto_rotorake_mk5: [
        `Working width of 50cm (20ins).`,
        `Cutting reel safety brake.`,
        `Contra-rotating reel with specially designed tipped blades for clean, consistent cut and maximum thatch removal.`,
        `Alternative blades for light scarifying.`,
        `Optional Brush Reels, Rolaspike Reel.`,
        `Depth of cut adjustment control is mounted on the handle to enable depth to be set whilst moving forwards.`,
        `User-friendly, operator presence controls designed for maximum operator safety.`,
        `Easy-fit collector box.`,
        `6.5hp petrol engine with independent drive to wheels and reel.`,
        `Careful weight distribution, slick tyres and full differential ensure ease of turning and minimal surface marking.`,
        `Optional artifical surface Brush Reels.`,
    ],
    veemo_mk2: [
        `3 fully floating units mounted on a chassis with support wheels to follow ground contours`,
        `Efficient hydraulic system with large volume tank`,
        `Direct hydraulic motor drive to each reel unit for maximum power transmission without belts`,
        `Tool free depth setting by micro control on each unit means fast, simple adjustment`,
        `Standard Cat.1, 3 point linkage for fast, easy coupling to tractor unit`,
        `Integral heavy duty oil cooler for all climate conditions`,
        `Fast ground coverage saving time and money`,
    ],
    hover_mower: [],
    brush_pro: [
        `Hydrostatic drive for forward/reverse`,
        `Rear brushes fold for transport and ease of storage`,
        `Electric start and activator lift to raise oscillating bruushes to transport height`,
        `Aggressive periodic use of oscillating brush keeps infill mobile and prevents surface compaction`,
        `Uses fewer passes than conventional drag brushing causing less compaction`,
        `Helps to maintain consistent infill levels throughout the pitch`,
        `Rear mounted brushes for routine maintenance`,
        `Incorporates tow hitch and is suitable for use with SSS1000`,
        `Brush options for different functions`,
    ],
    svr_1500_deep_cleaner: [
        `Provides maintenance cleaning, intensive cleaning, decompaction and surface rejuvenation`,
        `Includes stabalizing wheels`,
        `Rear brush for presentation`,
        `Easy to use hand wheel for working depth adjustment`,
        `Easy to remove filter sections`,
    ],
    sss1000: [
        `Essential to remove organic debris before it contaminates the surface`,
        `Important to remove any litter and potentially harmful debris before play`,
        `Brush height is easily adjustable without tools`,
        `Fast work rate helps to keep surfaces in play`,
        `Adjustable drawbar which lifts upright for easy storage, ball or jaw hitch`,
        `Wheel drive to the brush is diengaged by simple "pull & twist" clutch levers on each wheel for transport between sites`,
        `Unique spiral brush design reduces vibration and ensures contant brush contact with the surface`,
    ],
    osca_3: [
        `Aggressive brushing action keeps infill mobile and prevents surface compaction and loss of porosity`,
        `Maintains infill level at a constant depth giving consistent playing characteristics`,
        `Helps to prevent fibre damage caused by reduced infill levels`,
        `Uses fewer passes than conventional dragbrushes causing less compaction`,
        `Disperses top dressing quickly and evenly preventing excess material being left on the surface`,
        `Storage frame ensures handling and fitting the system to tractor is simple and safe. 
            It also helps to protect the system during movement and storage. Fitted with castor wheels`,
    ],
    varibrush: [
        `Multiple brushing action means fewer passes required and therefore reduced compaction`,
        `Easy to handle and attach system`,
        `Adjustable drawbar for towing height and length`,
        `Reversible frame to allow for brush wear`,
        `Can be used to brush top dressings into surfaces quickly and evenly preventing excess material being left on the surface`,
        `Helps to maintain consistent infill levels throughout the pitch`,
    ],
    powaspred: [
        `Ideal for spreading sand or rubber crumb infill`,
        `Handles sand based dressings even when damp`,
        `Infinitely variable spreading rates`,
        `Incorporates oscilitating base plate to reduce bridging`,
        `Rotating brush at point of discharge to ensure even spread`,
        `Cable controls for material shit off from tractor`,
    ],
    tractor_brush_combinations: [
        `Singleplay Frame`,
        `Twinplay Frame`,
        `Twin Implemenet Extension Arms`,
        `Flexicomb`,
    ],
    tractor_rake_and_brush_combinations: [
        `Singleplay Frame`,
        `Twinplay Frame`,
        `Twin Implemenet Extension Arms`,
        `Flexicomb`,
        `Fine Rake`,
    ],
    towed_brush_combination: [
        `Towed Single Frame - Manuel Lift`,
        `Towed Single Frame - Electric Lift`,
        `Twin Implement Extension Arms`,
        `Flexicomb Implement`,
    ],
    litamina: [
        `Essential to remove organic debris before it contaminates the surface`,
        `Important to remove any litter and potentially harmful debris before play`,
        `Standard cat 1, 3point linkage, pto drive`,
        `Hydraulic tip facility for easy emptying`,
        `"No tools required" simple brush adjustment`,
        `Large capacity mesh hopper which allows infill to be returned to the surface`,
    ],
    cyclone_8000: [
        `Kohler Command CH 440 Gasoline Engine`,
        `12v Controller for 360 degree nozzle rotation`,
        `Off-road trailer for ease of use`,

        `360 degree nozzle rotation`,
        `Nozzle Options for specific applications`,
        `Heavy-duty frame construction`,
        `Easily converted into a skid-mount`,
    ],
    cyclone_kb4: [],
    cyclone_squared: [],
    cyclone_mega: [],
    cyclone_pto: [],
    triangular_brush: [],

    // Harrod Products
    finesse_folding_target_goal: [],
    folding_target_goal: [],
    "4g_stadium_pro_goal_braided_nets": [],
    portaball_pro: [],
    "4g_stadium_pro_goal_hex_nets": [],
    "4g_stadium_goal": [],
    "4g_swivel_portagoal": [],
    "4g_portagoal": [],
    "4g_swivel_weighted_portagoal": [],
    "4g_euro_swivel_portagoal": [],
    "4g_weighted_portagoal": [],
    polygoal: [],
    "4g_portaball_portagoal_with_net": [],
    "4g_uefa_portagoal": [],
    "4g_euro_portagoal": [],
    slimline_bottom_hinged_net_support_bracket: [],
    "4g_net_hook_insertion_tool": [],
    heavyweight_freestanding_goal: [],
    folding_aluminum_goal: [],
    fixed_traing_goals: [],
    wheelaway_analyst_shelter: [],
    mini_target_goal: [],
    perimeter_poles: [],
    hi_raise_wheels: [],
    super_heavyweight_goal: [],
    heavyweight_goal: [],
    super_heavyweight_goal_with_locking_sockets: [],
    freestanding_steel_goal: [],
    folding_steel_goal: [],
    freestanding_aluminium_goal: [],
    u_peg_anchor_kit: [],

    // Line Marker Paint
    ecoline: [],
    direct: [],
    edge: [],
    transfer: [],
    extreme: [],
    lumen: [],
    clubline: [],
    line_out: [],
    agp: [],

    // Line Marker Machines
    hybrid: [],
    eco_pro: [],
    eco_club: [],
    eco_lite: [],
    fusion: [],
    classic: [],

    // Line Marker Accessories
    line_marking_handbook: [],
    linefix: [],
    grassroots_marking_kit: [],
    professional_marking_kit: [],
    initial_pitch_system: [],
    "200_m_string_line": [],
    pitch_marking_pegs: [],
    penalty_circle_marker: [],
    "100m_measuring_tape": [],
    guide_reel: [],
    mini_guide_reel: [],
    "3_4_5_triangle": [],
    kit_bag: [],
    "750_ml_aerosol": [],
    "6l_water_tank": [],
    "25l_paint_tank": [],
    spray_marker_service_kit: [],
    ecoclean_10l: [],
    concentrate_mixing_kit: [],
    contact_local_distributor: [],
};
