/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type EquipmentEvents = {
    _id: string;
    _type: "equipmentEvents";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    client?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "clients";
    };
    eventType?: "purchase" | "upgrade" | "replacement" | "repair" | "retired";
    lastEquipment?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "products";
    };
    currentEquipment?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "products";
    };
    reason?:
        | "End of Life"
        | "Upgrade"
        | "Performance Issue"
        | "Cost Savings"
        | "New Field Type"
        | "Expansion"
        | "Other";
    notes?: string;
    eventDate?: string;
};

export type Clients = {
    _id: string;
    _type: "clients";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    email?: string;
    phone?: string;
    company?: string;
    website?: string;
    status?: "active" | "paused" | "completed" | "inactive";
    equipmentOwned?: Array<{
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: "products";
    }>;
    equipmentNeeds?: Array<string>;
    equipmentInterest?: Array<{
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: "products";
    }>;
    notes?: string;
    lead?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "leads";
    };
    createdAt?: string;
};

export type Leads = {
    _id: string;
    _type: "leads";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    firstName?: string;
    lastName?: string;
    email?: string;
    phone?: string;
    company?: string;
    equipmentNeeds?: Array<string>;
    equipmentInterest?: Array<{
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: "products";
    }>;
    message?: string;
    source?: "Website Form" | "Email" | "Referral" | "Cold Outreach" | "Google" | "Other";
    status?: "new" | "contacted" | "qualified" | "lost" | "converted";
    priority?: "Low" | "Medium" | "High";
    createdAt?: string;
};

export type CuttingSpecifications = {
    _type: "cuttingSpecifications";
    cutting_width?: string;
    height_of_cut?: string;
    working_width?: string;
    working_depth?: string;
    cutter_performance?: string;
    cylinder?: string;
};

export type BrushSpecifications = {
    _type: "brushSpecifications";
    brushes?: string;
    number_of_brushes?: string;
    oscillating_brush?: string;
    rear_brush?: string;
};

export type EngineSpecifications = {
    _type: "engineSpecifications";
    engine?: string;
    engine_petrol?: string;
    tractor_power_requirement?: string;
    power_unit_requirement?: string;
};

export type Dimensions = {
    _type: "dimensions";
    width?: string;
    altWidth?: string;
    length?: string;
    altLength?: string;
    height?: string;
    altHeight?: string;
    tire_size?: string;
};

export type ProductSpecifications = {
    _type: "productSpecifications";
    specs_description?: string;
    features?: Array<string>;
    specifications?: ProductSpecifications;
    quality?: "1" | "2" | "3" | "4" | "5";
    video?: string;
};

export type Details = {
    _type: "details";
    specs_description?: string;
    features?: Array<string>;
    specifications?: ProductSpecifications;
    quality?: "1" | "2" | "3" | "4" | "5";
    video?: string;
};

export type UserSaves = {
    _id: string;
    _type: "userSaves";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    clerkId?: string;
    product?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "products";
    };
    createdAt?: string;
};

export type Products = {
    _id: string;
    _type: "products";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug?: Slug;
    description?: string;
    mainCategory?:
        | "Sport"
        | "Synthetic Turf"
        | "Natural Turf"
        | "Line Marker"
        | "Hand Tool"
        | "Goal"
        | "Debris Blower";
    tags?: Array<string>;
    brand?:
        | "Howardsons"
        | "Harrod Sports"
        | "Pitchmark"
        | "Buffalo Turbine"
        | "Eastman"
        | "Dennis"
        | "SISIS"
        | "Syn-Pro";
    image?: {
        asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
    };
    details?: Details;
    manual?: {
        asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
        };
        media?: unknown;
        _type: "file";
    };
    usedBy?:
        | "Golf"
        | "Soccer"
        | "American Football"
        | "Baseball"
        | "Lacrosse"
        | "Sports Turf"
        | "Synthetic Turf";
    popular?: boolean;
};

export type SanityImageCrop = {
    _type: "sanity.imageCrop";
    top?: number;
    bottom?: number;
    left?: number;
    right?: number;
};

export type SanityImageHotspot = {
    _type: "sanity.imageHotspot";
    x?: number;
    y?: number;
    height?: number;
    width?: number;
};

export type Slug = {
    _type: "slug";
    current?: string;
    source?: string;
};

export type Users = {
    _id: string;
    _type: "users";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    clerkId?: string;
    email?: string;
    name?: string;
    role?: "customer" | "admin";
    saves?: Array<{
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: "products";
    }>;
    dateJoined?: string;
};

export type SanityImagePaletteSwatch = {
    _type: "sanity.imagePaletteSwatch";
    background?: string;
    foreground?: string;
    population?: number;
    title?: string;
};

export type SanityImagePalette = {
    _type: "sanity.imagePalette";
    darkMuted?: SanityImagePaletteSwatch;
    lightVibrant?: SanityImagePaletteSwatch;
    darkVibrant?: SanityImagePaletteSwatch;
    vibrant?: SanityImagePaletteSwatch;
    dominant?: SanityImagePaletteSwatch;
    lightMuted?: SanityImagePaletteSwatch;
    muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
    _type: "sanity.imageDimensions";
    height?: number;
    width?: number;
    aspectRatio?: number;
};

export type SanityImageMetadata = {
    _type: "sanity.imageMetadata";
    location?: Geopoint;
    dimensions?: SanityImageDimensions;
    palette?: SanityImagePalette;
    lqip?: string;
    blurHash?: string;
    hasAlpha?: boolean;
    isOpaque?: boolean;
};

export type SanityFileAsset = {
    _id: string;
    _type: "sanity.fileAsset";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash?: string;
    extension?: string;
    mimeType?: string;
    size?: number;
    assetId?: string;
    uploadId?: string;
    path?: string;
    url?: string;
    source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
    _type: "sanity.assetSourceData";
    name?: string;
    id?: string;
    url?: string;
};

export type SanityImageAsset = {
    _id: string;
    _type: "sanity.imageAsset";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash?: string;
    extension?: string;
    mimeType?: string;
    size?: number;
    assetId?: string;
    uploadId?: string;
    path?: string;
    url?: string;
    metadata?: SanityImageMetadata;
    source?: SanityAssetSourceData;
};

export type Geopoint = {
    _type: "geopoint";
    lat?: number;
    lng?: number;
    alt?: number;
};

export type AllSanitySchemaTypes =
    | EquipmentEvents
    | Clients
    | Leads
    | CuttingSpecifications
    | BrushSpecifications
    | EngineSpecifications
    | Dimensions
    | ProductSpecifications
    | Details
    | UserSaves
    | Products
    | SanityImageCrop
    | SanityImageHotspot
    | Slug
    | Users
    | SanityImagePaletteSwatch
    | SanityImagePalette
    | SanityImageDimensions
    | SanityImageMetadata
    | SanityFileAsset
    | SanityAssetSourceData
    | SanityImageAsset
    | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
