import Cyclone8000Img from "@/public/products/debris-blowers/cyclone-8000.webp";

import { ProductSpecDescriptions } from "../product-spec-descriptions";
import { ProductFeatures } from "../product-features";
import { ProductSpecifications } from "../product-specifications";
import { EquipmentBrand } from "@/lib/types/brands";
import { ProductType } from "@/lib/types/product";

export const SoccerGoalProducts: ProductType[] = [
    {
        id: "sgp-1",
        name: "Finesse Folding Target Goal",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal", "freestanding"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-2",
        name: "Folding Target Goal",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal", "freestanding"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-3",
        name: "Portaball Pro",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal", "freestanding"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-4",
        name: "4G Swivel Portagoal",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal", "freestanding"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-5",
        name: "4G Portagoal",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal", "freestanding"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-6",
        name: "4G Swivel Weighted Portagoal",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal", "freestanding"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-7",
        name: "4G Euro Swivel Portagoal",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal", "freestanding"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-8",
        name: "4G Weighted Portagoal",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal", "freestanding"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-9",
        name: "Polygoal - 7v7/5v5",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal", "freestanding"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-10",
        name: "4G PortaBall Portagoal with Net",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal", "freestanding", "net", "netting"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-11",
        name: "4G Euro Portagoal",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal", "freestanding"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-12",
        name: "Heavyweight Freestanding Goal",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal", "freestanding"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-13",
        name: "Freestanding Steel Goal",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal", "freestanding"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-14",
        name: "Freestanding Aluminium Goal",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal", "freestanding"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-15",
        name: "FS1 Fold-away Goal",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal", "freestanding", "folding"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-16",
        name: "FS8 Folding Wheelaway Goal",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal", "freestanding", "folding"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-17",
        name: "Heavy Duty Galvanised Goal",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal", "freestanding"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-18",
        name: "Weighted UEFA Portagoal",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal", "freestanding"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-19",
        name: "Finesse 12 x 6ft Match Goal c/w Bag",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal", "freestanding"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-20",
        name: "Finesse 12 x 6ft Standard Goal",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal", "freestanding"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-21",
        name: "Finesse 6 x 4ft Standard Goal",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal", "freestanding"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-22",
        name: "Finesse 8 x 4ft Standard Goal",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal", "freestanding"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-23",
        name: "Folding Aluminium Goal",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal", "folding"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-24",
        name: "Folding Steel Goal",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal", "folding"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-25",
        name: "FS1 Fold-away Goal",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal", "folding"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-26",
        name: "FS8 Folding Wheelaway Goal",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal", "folding"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-27",
        name: "4G Fence Folding Goal",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal", "folding"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-28",
        name: "3G Foldaway Euro Portagoal",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal", "folding"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-29",
        name: "3G Hinged Portagoal - Senior",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal", "hinged"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-30",
        name: "4G Stadium Pro Goal - FIFA  Quality Package - Braided Nets",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal", "net", "netting"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-31",
        name: "4G Stadium Pro Goal",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-32",
        name: "4G Stadium Pro Goal - FIFA  Quality Package - Hex Nets",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal", "net", "netting"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-33",
        name: "4G Stadium Goal",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-34",
        name: "4G UEFA Portagoal",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-35",
        name: "Slimline Bottom Hinged Net Support Bracket",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-35",
        name: "4G Net Hook Insertion Tool",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-36",
        name: "Fixed Training Goals",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
    {
        id: "sgp-37",
        name: "4G Weighted Euro Portagoal - Senior",
        description: "Lightweight compact debris blower",
        mainCategory: "goal",
        tags: ["soccer", "goal"],
        brand: EquipmentBrand.BUFFALO_TURBINE,
        images: [Cyclone8000Img],
        details: {
            specs_description: ProductSpecDescriptions.cyclone_8000,
            features: ProductFeatures.cyclone_8000,
            specifications: {
                type: "goals",
                data: ProductSpecifications.javelin,
            },
            video: "",
        },
    },
];
